k9s:
  cluster: kind-kind
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
      - dnddy
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
