#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# yabai -m config                                 \
    # mouse_follows_focus          off            \
    # focus_follows_mouse          on             \
    # window_origin_display        default        \
    # window_placement             second_child   \
    # window_zoom_persist          on             \
    # window_topmost               off            \
    # window_shadow                on             \
    # window_animation_duration    0.0            \
    # window_animation_frame_rate  120            \
    # window_opacity_duration      0.0            \
    # active_window_opacity        1.0            \
    # normal_window_opacity        0.90           \
    # window_opacity               off            \
    # insert_feedback_color        0xffd75f5f     \
    # active_window_border_color   0xff775759     \
    # normal_window_border_color   0xff555555     \
    # window_border_width          4              \
    # window_border_radius         12             \
    # window_border_blur           on             \
    # window_border_hidpi          on             \
    # window_border                off            \
    # split_ratio                  0.50           \
    # split_type                   auto           \
    # auto_balance                 off            \
    # top_padding                  12             \
    # bottom_padding               12             \
    # left_padding                 12             \
    # right_padding                12             \
    # window_gap                   06             \
    # layout                       bsp            \
    # mouse_modifier               fn             \
    # mouse_action1                move           \
    # mouse_action2                resize         \
    # mouse_drop_action            swap


# function setup_space {
#   local idx="$1"
#   local name="$2"
#   local space=
#   echo "setup space $idx : $name"

#   space=$(yabai -m query --spaces --space "$idx")
#   if [ -z "$space" ]; then
#     yabai -m space --create
#   fi

#   yabai -m space "$idx" --label "$name"
# }

# yabai -m rule --add app="^System Settings$" manage=off
# # yabai -m rule --add app="^Finder$" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" manage=off
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add app="^Calculator$" manage=off
# yabai -m rule --add app="^Karabiner-Elements$" manage=off
# yabai -m rule --add app="^QuickTime Player$" manage=off
# yabai -m rule --add app="^Messages$" manage=off
# yabai -m rule --add app="^Bitwarden$" manage=off
# yabai -m rule --add app="^JetBrains Toolbox$" manage=off
# yabai -m rule --add app="^G Hub$" manage=off
# yabai -m rule --add app="^fig$" manage=off
# yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
# yabai -m rule --add label="Software Update" title="Software Update" manage=off
# yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add label="App Store" app="^App Store$" manage=off
# yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
# yabai -m rule --add app='CLion' manage=off
# yabai -m rule --add app='CLion' title='Settings' manage=off
# yabai -m rule --add app='CLion' title='Project Structure' manage=off
# yabai -m rule --add app='CLion' title='Edit configuration' manage=off
# yabai -m rule --add app='CLion' title='Preferences' manage=off

# echo "yabai configuration loaded.."
