"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#DA627D bg:#FCA17D)\
$git_metrics\
[](fg:#FCA17D)\
$line_break\
$python\
$character"""



right_format = """
$kubernetes\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$nodejs\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
$cmd_duration\
"""

add_newline = false

command_timeout = 100  

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
disabled = true
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
added_style = 'bold green'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = false

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = '☸ '
disabled = false
style = "bg:#86BBD8"
format = '[$symbol$context( \($namespace\))]($style) in '

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
